name: Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-latest
            ext: ""
          - name: Windows
            os: windows-latest
            ext: .exe

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install ninja-build tools
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure
        shell: bash
        run: |
          mkdir ./build
          cmake --no-warn-unused-cli \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CPP_COMPILER=g++ \
            -B ./build/ \
            -G "Ninja"

      - name: Build
        shell: bash
        run: |
          cmake --build ./build --config Release --target all -j 4

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: msbt_to_yaml${{ matrix.config.ext }}
          path: ./build/msbt_to_yaml/msbt_to_yaml${{ matrix.config.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
