name: Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Linux, Windows]
        os: [ubuntu-latest, windows-latest]
        ext: [~, .exe]
        c_compiler: [gcc, cl]
        cpp_compiler: [g++, cl]

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install Dependencies
        run: ${{ matrix.config.setup }}

      - name: Configure
        shell: bash
        run: |
          mkdir ./build
          cmake \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -B ./build/

      - name: Build
        shell: bash
        run: |
          cmake --build ./build --config Release --target all -j 4

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: msbt_to_yaml${{ matrix.config.ext }}
          path: ./build/msbt_to_yaml/msbt_to_yaml${{ matrix.config.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
