name: Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-20.04
            ext: ""
            runtime: linux-x64
            setup: |
              sudo apt-get update
              sudo apt-get install ninja-build cmake
              ninja --version
              cmake --version
              gcc --version
          - name: Windows
            os: windows-latest
            ext: .exe
            runtime: win-x64
            setup: |
              choco install ninja cmake
              ninja --version
              cmake --version

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install Dependencies
        run: ${{ matrix.config.setup }}

      - name: Configure
        shell: bash
        run: |
          mkdir ./build
          ${{ matrix.config.vars }} \
          cmake --no-warn-unused-cli \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_CXX_COMPILER=g++-13
            -DCMAKE_C_COMPILER=g++-13
            -B ./build/ \
            -G "Ninja"

      - name: Build
        shell: bash
        run: |
          cmake --build ./build --config Release --target all -j 4

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: msbt_to_yaml${{ matrix.config.ext }}
          path: ./build/msbt_to_yaml/msbt_to_yaml${{ matrix.config.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
